version: "3.9"

services:
  db:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oauth2_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    container_name: spring-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/oauth2_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  react:
    container_name: react-app
    build: ./react-oauth2
    ports:
      - "3000:3000"

volumes:
  db_data: