name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file spring-oauth2/pom.xml
      - name: Add coverage to PR
        # https://github.com/marketplace/actions/jacoco-report
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/spring-oauth2/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
