name: Generate Jacoco badges

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Build with Maven
        run: mvn -B test --file spring-oauth2/pom.xml

      - name: Generate JaCoCo badges
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: spring-oauth2/target/site/jacoco/jacoco.csv
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true

      - name: Push badges to "badges" branch
        run: |
          shopt -s extglob
          git checkout -b badges
          rm -rf !(.git|badges)
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "Autogenerated JaCoCo coverage badges"
          git push --force --set-upstream origin badges
