name: Java tests

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B test --file spring-oauth2/pom.xml

      - name: Generate JaCoCo badges
        # https://github.com/cicirello/jacoco-badge-generator
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: spring-oauth2/target/site/jacoco/jacoco.csv
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true

      - name: Push badges to "badges" branch
        # Checkout or create new branch "badges"
        # Delete all files and folders except ".git" and "badges"
        # Git add, commit, push newly created/modified badges
        # After success, badges will become available by paths
        # ../badges/badges/jacoco.svg and ../badges/badges/branches.svg
        run: |
          shopt -s extglob
          git checkout -b badges
          rm -rf !(badges)
          find . -type d -name ".github" -exec rm -r {} +
          find . -type f -name ".gitignore" -exec rm -r {} +
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add --all
          git commit -m "Autogenerate JaCoCo badges"
          git push --force --set-upstream origin badges
